export const propetiesAreaData = [
  {
    id: 1,
    img: "/assets/images/city1.webp",
    city: "Jersey City",
    listings: "25",
  },
  {
    id: 2,
    img: "/assets/images/city2.webp",
    city: "The Heights",
    listings: "3",
  },
  {
    id: 3,
    img: "/assets/images/city3.webp",
    city: "New Jersey State",
    listings: "25",
  },
  {
    id: 4,
    img: "/assets/images/city4.webp",
    city: "New York State",
    listings: "116",
  },
  {
    id: 5,
    img: "/assets/images/city5.webp",
    city: "New York",
    listings: "17",
  },
  {
    id: 6,
    img: "/assets/images/city6.webp",
    city: "Bayonne",
    listings: "5",
  },
  {
    id: 7,
    img: "/assets/images/city7.webp",
    city: "Greenville",
    listings: "17",
  },
  {
    id: 8,
    img: "/assets/images/city8.webp",
    city: "Manhattan",
    listings: "8",
  },
  {
    id: 9,
    img: "/assets/images/city9.webp",
    city: "Upper East Side",
    listings: "3",
  },
  {
    id: 10,
    img: "/assets/images/city10.webp",
    city: "Queens",
    listings: "4",
  },
  {
    id: 11,
    img: "/assets/images/city11.webp",
    city: "West Side",
    listings: "1",
  },
  {
    id: 12,
    img: "/assets/images/city12.webp",
    city: "West Village",
    listings: "1",
  },
];

export const propertiesData = [
  {
    id: 1,
    title: "Luxury House in Greenville",
    location: "Greenville, Jersey City",
    price: "860,000",
    category: "Houses",
    description:
      "This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.",
    bedrooms: 5,
    bathrooms: 6,
    area: "190 ft²",
    status: ["Featured", "Sales", "Active"],
    image: "/assets/images/property1.webp",
    agent: {
      name: "John Collins",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 1, photos: 6 },
  },
  {
    id: 2,
    title: "Modern Condo for Sale",
    location: "Manhattan, New York",
    price: "150,000",
    category: "Condos",
    description:
      "Beautiful, updated, ground-level Co-op apartment in the desirable Bay Terrace neighborhood.",
    bedrooms: 2,
    bathrooms: 2,
    area: "200 ft²",
    status: ["Featured", "Sales", "Open House"],
    image: "/assets/images/property2.webp",
    agent: {
      name: "Michael Sutther",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 0, photos: 6 },
  },
  {
    id: 3,
    title: "Apartment with Subunits",
    location: "Greenville, Jersey City",
    price: "999 / month",
    category: "Apartments",
    description:
      "Sesame Street international co-productions are educational children's television series.",
    bedrooms: 5,
    bathrooms: 2,
    area: "1,900 ft²",
    status: ["Featured", "Rentals", "Active"],
    image: "/assets/images/property3.webp",
    agent: {
      name: "Lora Smith",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 0, photos: 6 },
  },
  {
    id: 4,
    title: "Three Room Apartment",
    location: "Manhattan, New York",
    price: "550,000",
    category: "Apartments",
    description:
      "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood Floors.",
    bedrooms: 5,
    bathrooms: 2,
    area: "5,825 ft²",
    status: ["Featured", "Invest"],
    image: "/assets/images/property4.webp",
    agent: {
      name: "Mike Rutter",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 0, photos: 5 },
  },
  {
    id: 5,
    title: "Suburb Home for Sale",
    location: "The Heights, Jersey City",
    price: "1,000,000",
    category: "Houses",
    description:
      "Mineral Reserves: 2008 core drilling and testing proved 30 million tons of potential.",
    bedrooms: 5,
    bathrooms: 5,
    area: "2,900 ft²",
    status: ["Featured", "Invest", "Active"],
    image: "/assets/images/property5.webp",
    agent: {
      name: "Lara Black",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 1, photos: 7 },
  },
  {
    id: 6,
    title: "Gorgeous Home for Sale in Jersey",
    location: "Greenville, Jersey City",
    price: "770,000",
    category: "Houses",
    description:
      "This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.",
    bedrooms: 5,
    bathrooms: 6,
    area: "190 ft²",
    status: ["Featured", "Sales"],
    image: "/assets/images/property6.webp",
    agent: {
      name: "Martin Miller",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 0, photos: 6 },
  },
  {
    id: 7,
    title: "Luxury House in Greenville",
    location: "Greenville, Jersey City",
    price: "860,000",
    category: "For Sale",
    description:
      "This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.",
    bedrooms: 5,
    bathrooms: 6,
    area: "190 ft²",
    status: ["Featured", "Sales", "Active"],
    image: "/assets/images/property1.webp",
    agent: {
      name: "John Collins",
      profilePicture: "/assets/images/property1avatar.webp",
    },
    media: { videos: 1, photos: 6 },
  },
];

export const propertyCategoryData = [
  {
    id: 1,
    title: "Apartments",
    listings: 17,
    image: "/assets/images/property_category1.webp",
    size: "large",
  },
  {
    id: 2,
    title: "Condos",
    listings: 8,
    image: "/assets/images/property_category2.webp",
    size: "small",
  },
  {
    id: 3,
    title: "Duplexes",
    listings: 0,
    image: "/assets/images/property_category3.webp",
    size: "small",
  },
  {
    id: 4,
    title: "Houses",
    listings: 5,
    image: "/assets/images/property_category4.webp",
    size: "small",
  },
  {
    id: 5,
    title: "Offices",
    listings: 2,
    image: "/assets/images/property_category5.webp",
    size: "small",
  },
  {
    id: 6,
    title: "Villas",
    listings: 4,
    image: "/assets/images/property_category6.webp",
    size: "large",
  },
];
